# Generated by Django 5.0.4 on 2024-09-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
